### ISSUE TITLE
add Repository to DESCRIPTION

### ISSUE THREAD

**Issue by copernican** [joshuaulrich/pack#6]
Would it be possible to add the line

```
Repository: CRAN
```

to the `DESCRIPTION` file? This field is used by **`packrat`** during the RStudio Connect deployment process to figure out where to download package dependencies. The deployment process fails with a cryptic error without this field.

**Comment by joshuaulrich** [comment]
I believe CRAN adds and sets that field.  The last `pack` release was almost 10 years ago.  I suspect CRAN started adding that field sometime between then and now. :)  And likely before `packrat` existed.

I'm not inclined to set `Repository: CRAN` (or any other value) in the source code of a package.  That value appears to be used to point to the location where the tarball (the output of `R CMD build`) was acquired.  It doesn't seem right to set it in the source code, and it wouldn't surprise me if CRAN did not approve of that practice.

**Comment by copernican** [comment]
That makes sense, thank you. I cannot find any documentation on how CRAN sets the `Repository` field, so have followed up with cran-sysadmin@r-project.org for further information. Happy to share anything I discover.

**Comment by joshuaulrich** [comment]
Thanks, please let me know what, if anything, you find.
